# Generated by Django 4.0.5 on 2022-06-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='id_libro',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
