# Generated by Django 4.0.5 on 2022-06-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_id_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='id_usuario',
            new_name='nombre_usuario',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='id_libro',
            new_name='titulo',
        ),
    ]
